package baidu2

var ModelList = []string{
	"ERNIE-4.5-8K-Preview",
	"ERNIE-4.0-8K-Latest",
	"ERNIE-4.0-8K-Preview",
	"ERNIE-4.0-8K",
	"ERNIE-4.0-Turbo-8K-Latest",
	"ERNIE-4.0-Turbo-8K-Preview",
	"ERNIE-4.0-Turbo-8K",
	"ERNIE-4.0-Turbo-128K",
	"ERNIE-3.5-8K-Preview",
	"ERNIE-3.5-8K",
	"ERNIE-3.5-128K",
	"ERNIE-Speed-8K",
	"ERNIE-Speed-128K",
	"ERNIE-Speed-Pro-128K",
	"ERNIE-Lite-8K",
	"ERNIE-Lite-Pro-128K",
	"ERNIE-Tiny-8K",
	"ERNIE-Character-8K",
	"ERNIE-Character-Fiction-8K",
	"ERNIE-Novel-8K",
	"DeepSeek-V3",
	"DeepSeek-R1",
	"DeepSeek-R1-Distill-Qwen-32B",
	"DeepSeek-R1-Distill-Qwen-14B",
	"DeepSeek-R1-Distill-Qwen-7B",
	"DeepSeek-R1-Distill-Qwen-1.5B",
	"DeepSeek-R1-Distill-Llama-70B",
	"DeepSeek-R1-Distill-Llama-8B",
	"DeepSeek-R1-Distill-Qianfan-Llama-70B",
	"DeepSeek-R1-Distill-Qianfan-Llama-8B",
	"QwQ-32B",
}
